myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('about/', views.about),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/posts/urls.py
from django.urls import path
from . import views
app_name = 'posts'

urlpatterns = [
    path('', views.posts_list, name = "list"),
    path('<slug:slug>', views.post_page, name = "page"),
]

myproject/users/urls.py
from django.urls import path
from . import views
app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register')
]

myproject/posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True)
    
    def __str__(self):
        return self.title

myproject/users/models.py
from django.db import models

# Create your models here.

myproject/myproject/views.py
from django.shortcuts import render
def index(request):
    context = {
        'active_link': 'home'
    }
    return render(request, 'index.html', context)

def about(request):
    context = {
        'active_link':'about'
    }
    return render(request, 'about.html',context)

myproject/posts/views.py
from django.shortcuts import render
from .models import Post
# from django.http import HttpResponse

# Create your views here.
def posts_list(request):
    # posts = Post.objects.all()
    posts = Post.objects.all().order_by('date')
    context = {
        'active_link': 'posts',
        'posts':posts
    }
    return render(request,'posts/posts_list.html', context)
def post_page(request, slug):
    # return HttpResponse(slug)
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html',{'post':post} )

myproject/users/views.py
from django.shortcuts import render
def register(request):
    context = {
        'active_link': 'register'
    }
    return render(request, 'users/register.html', context)

myproject/posts/templates/posts/post_page.html
{% extends "base.html" %}
{% block title %}{{post.title}}{% endblock title %}
{% block head %}
{%load static%}
<link rel="stylesheet" href="{%static 'css/posts.css'%}">
{% endblock head %}
{% block header_image %}
<img src="{{post.banner.url}}" alt="{{post.title}}">

{% endblock header_image %}
{% block header_title %}{{post.title}}{% endblock header_title %}
{% block content %}
<div class="row justify-content-center">

        <div class="col-md-8">
        <article class = "post bg-light p-4 mb-4 rounded shadow-sm">
            <p class="post-date">{{post.date}}</p>
            <p class="post-body">{{post.body}}</p>
        </article>
        </div>

</div>
{% endblock content %}

myproject/posts/templates/posts/posts_list.html
{% extends "base.html" %}
{% block title %}POSTS LIST{% endblock title %}
{% block head %}
{%load static%}
<link rel="stylesheet" href="{%static 'css/posts.css'%}">
{% endblock head %}
{% block header_image %}
<img class="masthead-avatar mb-5" src="{% static 'assets/blog/posts.webp' %}" alt="..." />
{% endblock header_image %}
{% block header_title %}Posts List{% endblock header_title %}
{% block content %}
<div class="row justify-content-center">
    {% for post in posts  %}
        <div class="col-md-8">
        <article class = "post bg-light p-4 mb-4 rounded shadow-sm">
            <h2 class="post-title">
                <a href="{% url 'posts:page' slug=post.slug%}">
                {{post.title}}
                </a>
            </h2>
            <p class="post-date">{{post.date}}</p>
            <p class="post-body">{{post.body}}</p>
        </article>
        </div>
    {% endfor %}
</div>
{% endblock content %}

myproject/templates/about.html
{% extends "base.html"%}
{% load static %}
{% block title %}ABOUT{% endblock title %}

{% block header_image %}
<img class="masthead-avatar mb-5" src="{% static 'assets/blog/about.png' %}" alt="..." />
{% endblock header_image %}

{% block header_title %}ABOUT ME{% endblock header_title %}

myproject/templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
``    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock title %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        {% block head %}{% endblock head %}
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="#page-top">DJANGO BLOG</a>
                <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded {% if active_link == 'home' %}active{% endif %}" href="/">Home</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded {% if active_link == 'about' %}active{% endif %}" href="/about">About</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded {% if active_link == 'posts' %}active{% endif %}" href="{% url 'posts:list' %}">Posts</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded {% if active_link == 'register' %}active{% endif %}" href="users/register">Register</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead bg-primary text-white text-center">
            <div class="container d-flex align-items-center flex-column">
                <!-- Masthead Avatar Image-->
                {%block header_image%}
                {%endblock header_image%}
                <!-- Masthead Heading-->
                <h1 class="masthead-heading text-uppercase mb-0">{% block header_title %}{% endblock header_title %}</h1>
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Masthead Subheading-->
                {% comment %} <p class="masthead-subheading font-weight-light mb-0">Graphic Artist - Web Designer - Illustrator</p> {% endcomment %}
                {% block content %}{% endblock content %}
            </div>
        </header>

        <!-- Footer-->
        <footer class="footer text-center">
            <div class="container">
                <div class="row">
                    <!-- Footer Location-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">Location</h4>
                        <p class="lead mb-0">
                            2215 John Daniel Drive
                            <br />
                            Clark, MO 65243
                        </p>
                    </div>
                    <!-- Footer Social Icons-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">Around the Web</h4>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-linkedin-in"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-dribbble"></i></a>
                    </div>
                    <!-- Footer About Text-->
                    <div class="col-lg-4">
                        <h4 class="text-uppercase mb-4">About Freelancer</h4>
                        <p class="lead mb-0">
                            Freelance is a free to use, MIT licensed Bootstrap theme created by
                            <a href="http://startbootstrap.com">Start Bootstrap</a>
                            .
                        </p>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Copyright Section-->
        <div class="copyright py-4 text-center text-white">
            <div class="container"><small>Copyright &copy; Your Website 2023</small></div>
        </div>

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

myproject/templates/index.html
{% extends "base.html"%}
{% load static %}
{% block title %}HOME PAGE{% endblock title %}

{% block header_image %}
<img class="masthead-avatar mb-5" src="{% static 'assets/blog/homepage.png' %}" alt="..." />
{% endblock header_image %}


{% block header_title %}HOME PAGE{% endblock header_title %}

myproject/users/templates/users/register.html
{% extends "base.html" %}
{% load static %}
{% block title %}REGISTER{% endblock title %}

{% block header_image %}
<img class="masthead-avatar mb-5" src="{% static 'assets/blog/register.png' %}" alt="..." />
{% endblock header_image %}

{% block header_title %}Register A New User{% endblock header_title %}